exports.data = {
    title: 'BOOK FOUR, PART II, MAGICK',
    subtitle: 'PRELIMINARY REMARKS',
    pubName: 'Wieland and Co.',
    pubLocation: 'South Kensington',
    pubYear: '1913',
    folder: 'book4/2',
    creditFilename: 'credits-bookiv.pdf',
    images: [
        'cover-book4-2.jpg',
        'crowley-magician.jpg'
    ],
    links: [
        {text: 'info', url: 'https://www.100thmonkeypress.com/biblio/acrowley/books/book_4_part_2_1913/book_4_part_2_1913.htm'}
    ],
    contents: [
        {
            title: 'COVER AND TITLE',
            pageStart: 1,
            pageEnd: 4,
            prefix: '_',
            addPage: [
                {filename: '_cover.jpg'},
                {filename: '001.png', after: '_004.png'},
                {filename: '002.png', after: '_004.png'},
            ],
            pub: 'aa',
            number: 4,
            grade: [0],
        },
        {
            title: 'A NOTE',
            pageStart: 5,
            pageEnd: 7,
            prefix: '_',
            pub: 'aa',
            number: 4,
            grade: [0],
        },
        {
            title: 'PRELIMINARY REMARKS',
            pageStart: 3,
            pageEnd: 6,
            addPage: [
                {filename: '003image.png'},
            ],
            pub: 'aa',
            number: 4,
            grade: [0],
        },
        {
            title: 'THE TEMPLE',
            pageStart: 7,
            pageEnd: 9,
            skip:[8],
            pub: 'aa',
            number: 4,
            grade: [0],
        },
        {
            title: 'THE CIRCLE',
            pageStart: 11,
            pageEnd: 17,
            skip:[12],
            addPage: [
                {filename: '013image.png', after: '011.png'},
            ],
            pub: 'aa',
            number: 4,
            grade: [0],
        },
        {
            title: 'THE ALTAR',
            pageStart: 19,
            pageEnd: 23,
            skip:[20],
            addPage: [
                {filename: '021image.png', after: '019.png'},
                {filename: '022image.png', after: '022.png'},
            ],
            pub: 'aa',
            number: 4,
            grade: [0],
        },
        {
            title: 'THE SCOURAGE, THE DAGGER, AND THE CHAIN',
            pageStart: 25,
            pageEnd: 30,
            skip:[26],
            addPage: [
                {filename: '027image.png', after: '025.png'},
            ],
            pub: 'aa',
            number: 4,
            grade: [0],
        },
        {
            title: 'THE HOLY OIL',
            pageStart: 31,
            pageEnd: 35,
            skip:[32],
            pub: 'aa',
            number: 4,
            grade: [0],
        },
        {
            title: 'THE WAND',
            pageStart: 37,
            pageEnd: 62,
            skip:[38],
            addPage: [
                {filename: '039image.png'},
            ],
            pub: 'aa',
            number: 4,
            grade: [0],
        },
        {
            title: 'THE CUP',
            pageStart: 63,
            pageEnd: 78,
            skip:[64],
            pub: 'aa',
            number: 4,
            grade: [0],
        },
        {
            title: 'AN INTERLUDE',
            pageStart: 79,
            pageEnd: 92,
            skip:[80],
            pub: 'aa',
            number: 4,
            grade: [0],
        },
        {
            title: 'THE SWORD',
            pageStart: 93,
            pageEnd: 113,
            skip:[94],
            pub: 'aa',
            number: 4,
            grade: [0],
        },
        {
            title: 'THE PANTACLE',
            pageStart: 115,
            pageEnd: 129,
            skip:[116],
            addPage: [
                {filename: '117image.png', after:'115.png'},
                {filename: '130image.png', after:'129.png'},
            ],
            pub: 'aa',
            number: 4,
            grade: [0],
        },
        {
            title: 'THE LAMP',
            pageStart: 131,
            pageEnd: 136,
            skip:[132],
            pub: 'aa',
            number: 4,
            grade: [0],
        },
        {
            title: 'THE CROWN',
            pageStart: 137,
            pageEnd: 141,
            skip:[138],
            pub: 'aa',
            number: 4,
            grade: [0],
        },
        {
            title: 'THE ROBE',
            pageStart: 143,
            pageEnd: 146,
            skip:[144],
            pub: 'aa',
            number: 4,
            grade: [0],
        },
        {
            title: 'THE BOOK',
            pageStart: 147,
            pageEnd: 151,
            skip:[148],
            pub: 'aa',
            number: 4,
            grade: [0],
        },
        {
            title: 'THE BELL',
            pageStart: 153,
            pageEnd: 156,
            skip:[154],
            pub: 'aa',
            number: 4,
            grade: [0],
        },
        {
            title: 'THE LAMEN',
            pageStart: 157,
            pageEnd: 161,
            skip:[158],
            addPage: [
                {filename: '159image.png', after:'157.png'},
            ],
            pub: 'aa',
            number: 4,
            grade: [0],
        },
        {
            title: 'THE MAGICK FIRE',
            pageStart: 163,
            pageEnd: 171,
            skip:[164],
            addPage: [
                {filename: '165image.png', after:'163.png'},
            ],
            pub: 'aa',
            number: 4,
            grade: [0],
        },
        {
            title: 'GLOSSARY',
            pageStart: 173,
            pageEnd: 179,
            skip:[174],
            pub: 'aa',
            number: 4,
            grade: [0],
        },
        {
            title: 'NOTICE AND ORDER FORM',
            pageStart: 181,
            pageEnd: 184,
            pub: 'aa',
            number: 4,
            grade: [0],
        },
        {
            title: 'M∴M∴M∴',
            pageStart: 185,
            pageEnd: 186,
            pub: 'aa',
            number: 4,
            grade: [0],
        }
    ],
    publish: {
        instructions:[]
    }
};