java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/cover-title-and-contents.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/cover-title-and-contents.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/cover-title-and-contents_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/cover-title-and-contents_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/editorial.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/editorial.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/editorial_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/editorial_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/liber-jugorum.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/liber-jugorum.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/liber-jugorum_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/liber-jugorum_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/liber-armorum.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/liber-armorum.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/liber-armorum_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/liber-armorum_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/insit-naturae-regina-isis.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/insit-naturae-regina-isis.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/insit-naturae-regina-isis_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/insit-naturae-regina-isis_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/reviews.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/reviews.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/reviews_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/reviews_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/my-lady-of-the-breeches.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/my-lady-of-the-breeches.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/my-lady-of-the-breeches_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/my-lady-of-the-breeches_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/at-bordj-an-nus.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/at-bordj-an-nus.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/at-bordj-an-nus_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/at-bordj-an-nus_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/linos-isidos.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/linos-isidos.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/linos-isidos_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/linos-isidos_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/the-temple-of-solomon-the-king-part-4.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/the-temple-of-solomon-the-king-part-4.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/the-temple-of-solomon-the-king-part-4_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/the-temple-of-solomon-the-king-part-4_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/pan-to-artemis.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/pan-to-artemis.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/pan-to-artemis_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/pan-to-artemis_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/the-interpreter.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/the-interpreter.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/the-interpreter_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/the-interpreter_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/the-daughter-of-the-horseleech.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/the-daughter-of-the-horseleech.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/the-daughter-of-the-horseleech_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/the-daughter-of-the-horseleech_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/the-dreamer.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/the-dreamer.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/the-dreamer_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/the-dreamer_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/mr-todd.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/mr-todd.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/mr-todd_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/mr-todd_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/the-gnome.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/the-gnome.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/the-gnome_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/the-gnome_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/the-herb-dangerous-part-4.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/the-herb-dangerous-part-4.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/the-herb-dangerous-part-4_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/the-herb-dangerous-part-4_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/the-buddhist.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/the-buddhist.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/the-buddhist_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/the-buddhist_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/the-agnostic.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/the-agnostic.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/the-agnostic_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/the-agnostic_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/the-mantra-yogi.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/the-mantra-yogi.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/the-mantra-yogi_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/the-mantra-yogi_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/the-violinist.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/the-violinist.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/the-violinist_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/the-violinist_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/ehe.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/ehe.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/ehe_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/ehe_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/half-hours-with-famous-mahatmas-no-1.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/half-hours-with-famous-mahatmas-no-1.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/half-hours-with-famous-mahatmas-no-1_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/half-hours-with-famous-mahatmas-no-1_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/the-thief-taker.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/the-thief-taker.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/the-thief-taker_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/the-thief-taker_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/the-eyes-of-st-ljubov.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/the-eyes-of-st-ljubov.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/the-eyes-of-st-ljubov_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/the-eyes-of-st-ljubov_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/midsummer-eve.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/midsummer-eve.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/midsummer-eve_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/midsummer-eve_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/the-poetical-memory.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/the-poetical-memory.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/the-poetical-memory_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/the-poetical-memory_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/adela.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/adela.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/adela_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/adela_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/the-three-worms.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/the-three-worms.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/the-three-worms_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/the-three-worms_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/the-felon-flower.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/the-felon-flower.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/the-felon-flower_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/the-felon-flower_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/the-big-stick.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/the-big-stick.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/the-big-stick_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/the-big-stick_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/glaziers-houses.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/glaziers-houses.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/glaziers-houses_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/glaziers-houses_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/in-the-temple.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/in-the-temple.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/in-the-temple_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/in-the-temple_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/the-high-history-of-good-sir-palamedes-the-saracen-knight.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/the-high-history-of-good-sir-palamedes-the-saracen-knight.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/the-high-history-of-good-sir-palamedes-the-saracen-knight_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/the-high-history-of-good-sir-palamedes-the-saracen-knight_low.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-600dpi/advertisements.pdf ../scans/credits/pdf-600dpi/credits.pdf ./1.4/advertisements.pdf
java -jar pdfbox-app-2.0.8.jar PDFMerger ../scans/1.4/pdf-150dpi/advertisements_low.pdf ../scans/credits/pdf-150dpi/credits.pdf ./1.4/advertisements_low.pdf